# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

[managers.services]
items = [
    "auto-cpufreq",
    "bluetooth",
    "cups",
    "docker",
    "greetd",
    "mariadb",
    "postgresql",
    "tlp",
    "touchegg",
    "usbmuxd",
]

[managers.user_groups]
items = [
    "audio",
    "docker",
    "input",
    "video",
    "wheel",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "7zip",
    "adw-gtk-theme",
    "arandr",
    "auto-cpufreq",
    "baobab",
    "base",
    "base-devel",
    "bat",
    "bc",
    "bitwarden",
    "bitwarden-cli", # for qutebrowser
    "blueman",
    "bluez-utils",
    "bsp-layout",
    "bspwm",
    "btop",
    "caffeine-ng",
    "calf",
    "chafa",
    "cjson",
    "clang",
    "cups",
    "dk",
    "docker",
    "dosfstools",
    "downgrade",
    "dragon-drop",
    "dunst",
    "efibootmgr",
    "eww",
    "exfat-utils",
    "ffmpegthumbnailer",
    "flatpak",
    "freedownloadmanager",
    "gdb",
    "ghostscript",
    "gimp",
    "glfw",
    "gnome-characters",
    "gnome-disk-utility",
    "gnome-font-viewer",
    "go",
    "gopls",
    "greetd-regreet",
    "grim",
    "gtk-engine-murrine",
    "gvfs-afc",
    "gvfs-gphoto2",
    "gvfs-mtp",
    "helix",
    "hyprland",
    "i3lock",
    "ifuse",
    "imagemagick",
    "intel-ucode",
    "jq",
    "lazygit",
    "lf",
    "libimobiledevice",
    "light",
    "linux-lts",
    "loupe",
    "lua51",
    "luajit",
    "lua-language-server",
    "luarocks",
    "man-db",
    "man-pages",
    "mariadb",
    "marksman",
    "mpv",
    "mpv-mpris",
    "mtpfs",
    "nelua-git",
    "nitrogen",
    "ntfs-3g",
    "openresty",
    "openssl-1.1",
    "orca",
    "pamixer",
    "papirus-icon-theme",
    "pcmanfm",
    "pdfjs", # for qutebrowser
    "perl-file-mimeinfo",
    "picom",
    "playerctl",
    "polkit-gnome",
    "polybar",
    "postgresql",
    "pulsemixer",
    "python-adblock", # for qutebrowser
    "python-pipx",
    "python-tldextract", # for qutebrowser
    "qpwgraph",
    "qutebrowser",
    "rebos-git",
    "redshift",
    "rofi-wayland",
    "rust-analyzer",
    "rustup",
    "sassc",
    "scrot",
    "shfmt",
    "shotwell",
    "simple-scan",
    "snapshot",
    "sof-firmware",
    "sqlitebrowser",
    "stow",
    "stylua",
    "swaybg",
    "swaylock",
    "sxhkd",
    "tailscale",
    "tcc",
    "terminator",
    "tlp",
    "touchegg",
    "transmission-gtk",
    "trash-cli",
    "tree",
    "ttf-dejavu-nerd",
    "ttf-ms-win11-auto",
    "unrar",
    "usbmuxd",
    "visual-studio-code-bin",
    "vulkan-intel",
    "wezterm",
    "wget",
    "wl-clipboard",
    "x42-plugins",
    "xclip",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "xdg-ninja",
    "xdg-user-dirs-gtk",
    "xdman-beta-bin",
    "xfce4-settings",
    "xorg-xev",
    "xorg-xinput",
    "xorg-xkill",
    "xorg-xsetroot",
    "yay",
    "yay-debug",
    "zam-plugins",
    "zathura",
    "zathura-pdf-mupdf",
    "zed",
    "zenity",
    "zram-generator"
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    "app.drey.EarTag",
    "app.zen_browser.zen",
    "com.brave.Browser",
    "com.discordapp.Discord",
    "com.github.joseexposito.touche",
    "com.github.tchx84.Flatseal",
    "com.obsproject.Studio",
    "com.simplenote.Simplenote",
    "com.spotify.Client",
    "com.usebottles.bottles",
    "com.valvesoftware.Steam",
    "dev.bragefuglseth.Keypunch",
    "io.github.swordpuffin.rewaita",
    "org.gnome.Boxes",
    "org.gnome.World.PikaBackup",
    "org.gtk.Gtk3theme.adw-gtk3",
    "org.gtk.Gtk3theme.adw-gtk3-dark",
    "org.kde.kdenlive",
    "org.localsend.localsend_app",
    "org.onlyoffice.desktopeditors",
    "org.ppsspp.PPSSPP",
    "org.soundconverter.SoundConverter",
    "org.telegram.desktop",
    "org.vinegarhq.Sober",
    "page.codeberg.libre_menu_editor.LibreMenuEditor",
]

[managers.luarocks5_1]
items = [
    "argparse",
    "bcrypt",
    "busted",
    "cqueues",
    "lapis",
    "lsqlite3",
    "lua-cjson",
    "luafilesystem",
    "lua-resty-http",
    "lua-resty-mail",
    "luasec",
    "moonscript",
    "tableshape",
    "web_sanitize"
]

[managers.luarocks5_4]
items = [
    "argparse",
    "bcrypt",
    "busted",
    "cqueues",
    "lapis",
    "lsqlite3",
    "lua-cjson",
    "luafilesystem",
    "lua-resty-http",
    "lua-resty-mail",
    "luasec",
    "moonscript",
    "tableshape",
    "web_sanitize"
]

[managers.npm]
items = [
    "autocannon",
    "bash-language-server",
    "browser-sync",
    "corepack",
    "dockerfile-language-server-nodejs",
    "emmet-language-server",
    "emmet-ls",
    "intelephense",
    "node-gyp",
    "nopt",
    "npm",
    "prettier",
    "semver",
    "tailwindcss",
    "@tailwindcss/cli",
    "@tailwindcss/language-server",
    "tree-sitter-cli",
    "typescript",
    "typescript-language-server",
    "vscode-langservers-extracted"
]

[managers.pipx]
items = [
    "black",
    "djlint",
    "jedi-language-server",
    "pyright",
]
